# 1. Python 3.9 버전을 기반 이미지로 사용합니다.
#    이는 가볍고 안정적인 환경을 제공합니다.
FROM python:3.9-slim

# 2. 작업 디렉토리를 /app으로 설정합니다.
#    모든 파일은 이 디렉토리 내에서 관리됩니다.
WORKDIR /app

# 3. 애플리케이션의 종속성 파일(requirements.txt)을 컨테이너에 복사합니다.
#    이는 캐시를 활용하여 종속성 설치 시간을 단축합니다.
COPY requirements.txt requirements.txt

# 4. 종속성 파일을 기반으로 필요한 라이브러리들을 설치합니다.
#    여기서는 Flask를 설치합니다.
RUN pip install -r requirements.txt

# 5. 모든 소스 코드를 컨테이너의 /app 디렉토리로 복사합니다.
COPY . .

# 6. Flask 애플리케이션을 실행하기 위한 환경 변수를 설정합니다.
ENV FLASK_APP=backend.py

# 7. 컨테이너가 5000번 포트를 외부에 노출하도록 설정합니다.
EXPOSE 5000

# 8. 컨테이너가 시작될 때 실행할 명령어를 정의합니다.
#    gunicorn은 프로덕션 환경에서 Flask 애플리케이션을 실행하는 데 사용되는
#    안정적이고 강력한 WSGI 서버입니다.
#    -b 0.0.0.0:5000: 모든 네트워크 인터페이스에서 5000번 포트를 리스닝합니다.
#    --workers 4: 4개의 워커 프로세스를 사용하여 동시 요청을 처리합니다.
#    backend:app: 'backend' 모듈의 'app' 객체를 실행합니다.
CMD ["gunicorn", "-b", "0.0.0.0:5000", "--workers", "4", "backend:app"]
